### ISSUE TITLE
v1.0.0 causes export failure in Godot v3.3.2.stable.mono.official

### ISSUE THREAD

**Issue by Nosrick** [Atlinx/Godot-Mono-CustomResourceRegistry#5]
I'm trying to export a project that uses this addon, but I get the following errors when trying to export:
`C:\Projects\JoyGodot\addons\CustomResourceRegistry\Plugin.cs(15,24): The type or namespace name 'EditorPlugin' could not be found (are you missing a using directive or an assembly reference?)`
`C:\Projects\JoyGodot\addons\CustomResourceRegistry\Plugin.cs(20,24): 'Plugin._EnterTree()': no suitable method found to override`
`C:\Projects\JoyGodot\addons\CustomResourceRegistry\Plugin.cs(29,24): 'Plugin._ExitTree()': no suitable method found to override`

These are preventing me from exporting my project. If there is a way to exclude this addon from the export process, I would appreciate any information on that, otherwise, I'm not sure what I can do here, other than remove the addon entirely.

This may also be a general Godot issue, I'm not sure.

**Comment by Atlinx** [comment]
You can exclude the plugin files during export as documented in this [Godot issue](https://github.com/godotengine/godot/issues/3646).

But I feel like this may be a Godot mono problem since GDScript plugins work fine on export. I'll have to do some more testing on my side to get to the bottom of this.

**Comment by Nosrick** [comment]
> You can exclude the plugin files during export as documented in this [Godot issue](https://github.com/godotengine/godot/issues/3646).

This doesn't seem to work; the plugin doesn't show up under the file tree, and even putting the folder (absolute or relative, doesn't make a difference) in the "exclude" filter still causes a failure.

I believe this probably is a Godot Mono issue, I think you're right.

**Comment by Atlinx** [comment]
I've now fixed this issue in the latest release (v1.0.1). I had to wrap the EditorPlugin in preprocessor directives such that Godot will ignore the EditorPlugin class when building. I guess GDScript doesn't need this sort of stuff since it is an interpreted language so it does not care about editor code shipping with regular code -- as long as it doesn't read this editor code the code works fine.
